import { useState } from "react"
import { ArrowRight, Check, Copy, Github, LockKeyhole, Smartphone, Terminal } from "lucide-react"
import { Mark } from "@/components/mark"

type DemoTab = "run" | "wait" | "send" | "pipe"
type Demo = { command: string; description: string; output: string[]; notification: { title: string; body: string; status: string } }

const demos: Record<DemoTab, Demo> = {
  run: { command: "chifla run -t 'Build de producción' npm run build", description: "Ejecutá un comando y recibí el resultado cuando termina.", output: ["$ chifla run -t 'Build de producción' npm run build", "> vite build", "✓ 1671 modules transformed.", "✓ built in 1.33s", "sent → inbox [exit 0 · 1.33s]"], notification: { title: "Build de producción", body: "npm run build terminó correctamente en 1.33 s.", status: "exit 0" } },
  wait: { command: "chifla wait 14280 -t 'Entrenamiento del modelo'", description: "Seguí un proceso que ya está corriendo, sin reiniciarlo.", output: ["$ chifla wait 14280 -t 'Entrenamiento del modelo'", "watching python (PID 14280)...", "process completed after 24m 12s.", "sent → inbox [exit 0]"], notification: { title: "Entrenamiento del modelo", body: "python terminó correctamente después de 24 min.", status: "exit 0" } },
  send: { command: "chifla -c deploys -p urgent 'Canary listo en edge'", description: "Mandá una alerta puntual desde CI o tus scripts.", output: ["$ chifla -c deploys -p urgent 'Canary listo en edge'", "encrypting payload locally...", "sent → #deploys [urgent]"], notification: { title: "Canary listo en edge", body: "El tráfico está al 100% sin anomalías reportadas.", status: "urgent" } },
  pipe: { command: "git log -1 --oneline | chifla -t 'Nuevo release'", description: "Enviá logs o cualquier salida estándar a tu teléfono.", output: ["$ git log -1 --oneline | chifla -t 'Nuevo release'", "a13f8b2 feat: ship notifications", "sent → inbox"], notification: { title: "Nuevo release", body: "a13f8b2 feat: ship notifications", status: "delivered" } },
}

const steps = [["01", "Prepará tu dispositivo", "Abrí Chiflame, activá las notificaciones y creá tu buzón."], ["02", "Vinculá la terminal", "Instalá el CLI y escaneá el código de emparejamiento."], ["03", "Seguí trabajando", "Envolvé un comando o mandá una alerta cuando la necesites."]]
const guarantees = [["Cifrado en origen", "El contenido se cifra en tu terminal antes de salir a la red."], ["Servidor ciego", "La infraestructura sólo conserva datos cifrados, nunca el texto de tus alertas."], ["Código abierto", "Podés revisar la implementación y desplegar tu propia instancia."]]

export function App() {
  const [activeTab, setActiveTab] = useState<DemoTab>("run")
  const [copied, setCopied] = useState(false)
  const demo = demos[activeTab]
  async function copyCommand() { await navigator.clipboard.writeText(demo.command); setCopied(true); window.setTimeout(() => setCopied(false), 1800) }

  return <div className="min-h-screen bg-black text-zinc-100 antialiased">
    <header className="border-b border-white/[0.08]"><div className="mx-auto flex h-16 max-w-6xl items-center justify-between px-5 sm:px-6"><a href="#top" className="flex items-center gap-2.5" aria-label="Chiflame, inicio"><Mark className="h-7 w-7" /><span className="text-sm font-medium tracking-tight text-white">chiflame</span></a><nav className="hidden items-center gap-6 text-xs text-zinc-400 md:flex" aria-label="Navegación principal"><a className="transition-colors hover:text-white" href="#como-funciona">Cómo funciona</a><a className="transition-colors hover:text-white" href="#privacidad">Privacidad</a><a className="transition-colors hover:text-white" href="https://github.com/b45t3rr/chiflame" target="_blank" rel="noreferrer">GitHub</a></nav><a href="https://app.chifla.me" className="rounded-md bg-white px-3 py-1.5 text-xs font-medium text-black transition-colors hover:bg-zinc-200">Abrir app</a></div></header>
    <main id="top"><section className="mx-auto max-w-6xl px-5 pb-20 pt-20 sm:px-6 sm:pb-28 sm:pt-28"><div className="mx-auto max-w-3xl text-center"><p className="mb-6 font-mono text-xs text-zinc-500">CLI notifications, privately delivered.</p><h1 className="text-balance text-4xl font-semibold tracking-[-0.045em] text-white sm:text-6xl md:text-7xl">Terminá tu trabajo. Chiflame te avisa.</h1><p className="mx-auto mt-6 max-w-2xl text-pretty text-base leading-7 text-zinc-400 sm:text-lg">Recibí en tu teléfono el resultado de builds, deploys y procesos largos. Sin dejar la terminal abierta ni entregar el contenido de tus alertas.</p><div className="mt-9 flex flex-col justify-center gap-3 sm:flex-row"><a href="https://app.chifla.me" className="inline-flex items-center justify-center gap-2 rounded-md bg-white px-5 py-2.5 text-sm font-medium text-black transition-colors hover:bg-zinc-200">Configurar Chiflame <ArrowRight className="h-4 w-4" /></a><a href="https://github.com/b45t3rr/chiflame" target="_blank" rel="noreferrer" className="inline-flex items-center justify-center gap-2 rounded-md border border-white/[0.12] px-5 py-2.5 text-sm font-medium text-zinc-200 transition-colors hover:border-white/25 hover:bg-white/[0.05]"><Github className="h-4 w-4" /> Ver código</a></div></div>
      <div className="mt-16 overflow-hidden rounded-lg border border-white/[0.12] bg-zinc-950 sm:mt-20"><div className="flex flex-col border-b border-white/[0.08] px-4 py-3 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-2 text-xs font-mono text-zinc-500"><Terminal className="h-3.5 w-3.5" />chifla</div><div className="mt-3 flex gap-1 sm:mt-0" role="tablist" aria-label="Ejemplos de comandos">{(Object.keys(demos) as DemoTab[]).map((tab) => <button key={tab} type="button" role="tab" aria-selected={activeTab === tab} onClick={() => setActiveTab(tab)} className={`rounded px-2.5 py-1 font-mono text-xs transition-colors ${activeTab === tab ? "bg-white/[0.1] text-white" : "text-zinc-500 hover:text-zinc-300"}`}>{tab}</button>)}</div></div><div className="grid lg:grid-cols-[1.35fr_0.85fr]"><div className="p-5 sm:p-7"><p className="mb-5 text-xs text-zinc-500">{demo.description}</p><div className="flex items-center gap-3 rounded-md border border-white/[0.08] bg-black px-3 py-2.5 font-mono text-xs text-zinc-200"><span className="select-none text-emerald-400">$</span><code className="min-w-0 flex-1 truncate">{demo.command}</code><button type="button" onClick={copyCommand} className="rounded p-1 text-zinc-500 transition-colors hover:text-white" aria-label="Copiar comando">{copied ? <Check className="h-3.5 w-3.5 text-emerald-400" /> : <Copy className="h-3.5 w-3.5" />}</button></div><div className="mt-6 space-y-2 font-mono text-xs leading-5">{demo.output.map((line) => <p key={line} className={line.startsWith("sent") ? "text-emerald-400" : line.startsWith("$") ? "text-zinc-200" : "text-zinc-500"}>{line}</p>)}</div></div><div className="border-t border-white/[0.08] bg-white/[0.02] p-5 sm:p-7 lg:border-l lg:border-t-0"><div className="mx-auto max-w-xs rounded-xl border border-white/[0.12] bg-zinc-900 p-4 shadow-2xl"><div className="flex items-start justify-between gap-3"><div className="flex items-center gap-2.5"><Mark className="h-7 w-7" /><div><p className="text-xs font-medium text-white">Chiflame</p><p className="mt-0.5 text-[10px] text-zinc-500">ahora</p></div></div><span className="rounded border border-emerald-400/20 bg-emerald-400/10 px-1.5 py-0.5 font-mono text-[10px] text-emerald-400">{demo.notification.status}</span></div><h2 className="mt-5 text-sm font-medium text-white">{demo.notification.title}</h2><p className="mt-1.5 text-xs leading-5 text-zinc-400">{demo.notification.body}</p><div className="mt-5 flex items-center gap-2 border-t border-white/[0.08] pt-3 font-mono text-[10px] text-zinc-500"><LockKeyhole className="h-3.5 w-3.5 text-emerald-400" />Descifrado en tu dispositivo</div></div></div></div></div></section>
      <section id="como-funciona" className="border-y border-white/[0.08]"><div className="mx-auto max-w-6xl px-5 py-20 sm:px-6 sm:py-24"><div className="max-w-xl"><p className="font-mono text-xs text-zinc-500">CONFIGURACIÓN</p><h2 className="mt-3 text-3xl font-semibold tracking-[-0.04em] text-white sm:text-4xl">Listo para cuando tu terminal termina.</h2></div><ol className="mt-12 grid gap-px overflow-hidden rounded-lg border border-white/[0.08] bg-white/[0.08] md:grid-cols-3">{steps.map(([number, title, description]) => <li key={number} className="bg-black p-6 sm:p-7"><p className="font-mono text-xs text-zinc-500">{number}</p><h3 className="mt-8 text-base font-medium text-white">{title}</h3><p className="mt-2 max-w-xs text-sm leading-6 text-zinc-400">{description}</p></li>)}</ol></div></section>
      <section id="privacidad" className="mx-auto max-w-6xl px-5 py-20 sm:px-6 sm:py-24"><div className="grid gap-12 lg:grid-cols-[0.8fr_1.2fr] lg:gap-20"><div><p className="font-mono text-xs text-zinc-500">PRIVACIDAD POR DISEÑO</p><h2 className="mt-3 text-3xl font-semibold tracking-[-0.04em] text-white sm:text-4xl">Tus alertas son tuyas.</h2><p className="mt-5 text-sm leading-6 text-zinc-400">Chiflame está construido para entregar una notificación, no para leerla. Las garantías técnicas están disponibles para revisar en el repositorio.</p><a href="https://github.com/b45t3rr/chiflame" target="_blank" rel="noreferrer" className="mt-6 inline-flex items-center gap-2 text-sm text-white underline decoration-zinc-600 underline-offset-4 transition-colors hover:decoration-white">Revisar la implementación <ArrowRight className="h-3.5 w-3.5" /></a></div><div className="divide-y divide-white/[0.08] border-y border-white/[0.08]">{guarantees.map(([title, description]) => <div key={title} className="py-6 first:pt-0 last:pb-0"><h3 className="text-sm font-medium text-white">{title}</h3><p className="mt-2 max-w-lg text-sm leading-6 text-zinc-400">{description}</p></div>)}</div></div></section>
      <section className="border-t border-white/[0.08] bg-zinc-950"><div className="mx-auto max-w-3xl px-5 py-20 text-center sm:px-6 sm:py-24"><Smartphone className="mx-auto h-5 w-5 text-zinc-500" /><h2 className="mt-5 text-3xl font-semibold tracking-[-0.04em] text-white sm:text-5xl">No esperes frente a la consola.</h2><p className="mx-auto mt-5 max-w-xl text-base leading-7 text-zinc-400">Configurá tu dispositivo y recibí alertas privadas donde estés.</p><a href="https://app.chifla.me" className="mt-8 inline-flex items-center gap-2 rounded-md bg-white px-5 py-2.5 text-sm font-medium text-black transition-colors hover:bg-zinc-200">Abrir Chiflame <ArrowRight className="h-4 w-4" /></a></div></section>
    </main><footer className="mx-auto flex max-w-6xl flex-col gap-4 px-5 py-8 text-xs text-zinc-500 sm:flex-row sm:items-center sm:justify-between sm:px-6"><div className="flex items-center gap-2"><Mark className="h-5 w-5" /><span>Chiflame</span></div><div className="flex gap-5"><a className="hover:text-white" href="https://github.com/b45t3rr/chiflame" target="_blank" rel="noreferrer">GitHub</a><a className="hover:text-white" href="https://github.com/b45t3rr/chiflame/blob/main/LICENSE" target="_blank" rel="noreferrer">MIT License</a></div></footer>
  </div>
}
